// <auto-generated />
namespace DataAccess_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_Minimum_Credit_For_Loan_Customer_Status_Loan_Status_End_Date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Minimum_Credit_For_Loan_Customer_Status_Loan_Status_End_Date));
        
        string IMigrationMetadata.Id
        {
            get { return "202510050857394_Add_Minimum_Credit_For_Loan_Customer_Status_Loan_Status_End_Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
