// <auto-generated />
namespace DataAccess_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_Customer_Email_Remove_Loan_InstallementInterval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Customer_Email_Remove_Loan_InstallementInterval));
        
        string IMigrationMetadata.Id
        {
            get { return "202510070822004_Add_Customer_Email_Remove_Loan_InstallementInterval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
