using System;
using System.ComponentModel.DataAnnotations; 
using System.Text;
using System.Threading.Tasks;

namespace BusinessLogic_Layer.DTOs
{
    public class CustomerDTO
    {
        // Customer_Id is auto-generated by the database for Create operations
        public int Customer_Id { get; set; }

        //Name is required.
        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }

        //Address is required.
        [Required(ErrorMessage = "Address is required.")]
        public string Address { get; set; }

        //Email is required and format is valid.
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Email format is invalid.")]
        public string Email { get; set; }

        // Credit_Score is auto-generated on Create, updated on Edit (checked by Credit Score rule)
        // If this DTO is used for Update, we rely on the controller logic for non-negative check.
        public float Credit_Score { get; set; }

        //Gender is required 
        [Required(ErrorMessage = "You must select a gender")]
        // If Gender is strictly 0.0 or 1.0, you can add:
        [Range(1.0, 2.0, ErrorMessage = "Gender must be 0 or 1.")]
        public float Gender { get; set; }

        //Card Number is required and must be a positive number.
        [Required(ErrorMessage = "A valid Card Number is required.")]
        [Range(1, double.MaxValue, ErrorMessage = "A valid Card Number is required.")]
        public string Card_Number { get; set; }

        //Monthly Income is required and must be a positive number (> 0).
        [Required(ErrorMessage = "Monthly Income must be a positive number.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Monthly Income must be a positive number.")]
        public float Monthly_Income { get; set; }

        // Status is auto-generated
        public string Status { get; set; }

    }
}